---
network_address_mode: static
network_address: 129.110.92.80/24
network_gateway: 129.110.92.1
network_dns_mode: static

certbot_contact_email: michael.aldridge@utdallas.edu
certbot_webroot: /var/www/home/
certbot_domain: lug.utdallas.edu

jekyll_site_url: lug.utdallas.edu
jekyll_site_path: /var/www/home
jekyll_site_name: utdlug
jekyll_source_url: https://github.com/utdlug/utdlug.github.io.git
jekyll_use_ssl: true
jekyll_use_letsencrypt: true

xbps_repository_main: /mnt/mirror/void/current
xbps_repository_nonfree: /mnt/mirror/void/current/nonfree
xbps_repository_multilib: /mnt/mirror/void/current/multilib
xbps_repository_multilib_nonfree: /mnt/mirror/void/current/multilib/nonfree
